### ISSUE TITLE
Simplified UI: Tweet

### ISSUE THREAD

**Issue by data-101** [InetIntel/ioda-ui#57]

**Comment by arvinpoddar** [comment]
After doing some research into the Twitter API, the Twitter WebIntent object (this is the object created anytime you "Share on Twitter" on a website) doesn't support the direct inclusion of images. Images can be added afterwards as a direct upload. While there are workarounds that involve using the Twitter API, being able to create tweets with images requires Twitter's manually reviewed approval, and will pose significant development work on our side since we will have to ask for Twitter credentials and manage this data on our platform. These workarounds wouldn't be entirely free either. 

Twitter API Pricing: https://developer.twitter.com/en/products/twitter-api
